api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "noxrev-bundle-discount"
type = "function"
uid = "eae2452c-f0c6-ab86-6477-f372cfb483f18ebde999"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.lines.discounts.generate.run"
  input_query = "src/cart_lines_discounts_generate_run.graphql"
  export = "cart-lines-discounts-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
